### PR TITLE
Minor refactoring

### PR DESCRIPTION
**Pull request by JCotton1123**

### CODE REVIEW

**Comment by ciarlatano** [comment]
Hi Sandy,
just used the Friday night to add support for my Orvibo wifi co sensor using your code, including mqtt state publish and configuring an homebridge-mqttthing accessory.
Long story short, I have now a CO sensor in my home app, supporting battery, co level, alarm, charging statuses and making me happy.

I can post every modification done but let me say now just what was  the clue: the following packets sent by the sensor:

Socket ->  {"cmd":146,"serial":4,"uid":"a020a60c66d1","deviceId":"0","zeroOffset":48643,"k30Value":17924,"k50Value":55300,"k80Value":31492,"k100Value":13318,"k150Value":25605,"alarmValue":13318}
Socket ->  {"cmd":144,"serial":10,"uid":"a020a60c66d1","deviceId":"0","powerStatus":0,"deviceStatus":0,"muteStatus":1,"voiceStatus":0,"brightness":15,"alarmLevel":1}
Socket ->  {"cmd":143,"serial":1475053499,"uid":"a020a60c66d1","deviceId":"0","timestamp":1475053499,"batteryValue":100,"coConcentration":0,"hchoConcentration":-1,"temperature":-1,"humidity":-1,"alarmStatus":0}

Playing with coConcentration, alarmStatus, batteryValue and powerStatus I got all needed values.

Thank you very much!

**Comment by JCotton1123** [comment]
@sandysound is this something you'd consider accepting or should I just close the PR?

**Review by sandysound — APPROVED** [review]
Looks great, feel free to merge!

**Comment by sandysound** [comment]
Hey @JCotton1123 sorry I must have missed this! Thanks for reminding me :)

**Comment by JCotton1123** [comment]
@sandysound thank you! I don't have write access - can you merge when you get a chance :)

**Comment by sandysound** [comment]
Done!

**Pull request merged**
